<?php

use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('districts')->delete();
        $ids = DB::table('states')->lists('id', 'code');
        // states
        DB::table('districts')->insert(
            [
                /* ANDAMAN AND NICOBAR */
                ['state_id' => $ids['AN'], 'code' => 'NI', 'name' => 'Nicobar'],
                ['state_id' => $ids['AN'], 'code' => 'NA', 'name' => 'North and Middle Andaman'],
                ['state_id' => $ids['AN'], 'code' => 'SA', 'name' => 'South Andaman'],
                /* ANDHRA PRADESH */
                ['state_id' => $ids['AP'], 'code' => 'AN', 'name' => 'Anantapur'],
                ['state_id' => $ids['AP'], 'code' => 'CH', 'name' => 'Chittoor'],
                ['state_id' => $ids['AP'], 'code' => 'EG', 'name' => 'East Godavari'],
                ['state_id' => $ids['AP'], 'code' => 'GU', 'name' => 'Guntur'],
                ['state_id' => $ids['AP'], 'code' => 'CU', 'name' => 'Kadapa'],
                ['state_id' => $ids['AP'], 'code' => 'KR', 'name' => 'Krishna'],
                ['state_id' => $ids['AP'], 'code' => 'KU', 'name' => 'Kurnool'],
                ['state_id' => $ids['AP'], 'code' => 'NE', 'name' => 'Sri Potti Sriramulu Nellore'],
                ['state_id' => $ids['AP'], 'code' => 'PR', 'name' => 'Prakasam'],
                ['state_id' => $ids['AP'], 'code' => 'SR', 'name' => 'Srikakulam'],
                ['state_id' => $ids['AP'], 'code' => 'VS', 'name' => 'Visakhapatnam'],
                ['state_id' => $ids['AP'], 'code' => 'VZ', 'name' => 'Vizianagaram'],
                ['state_id' => $ids['AP'], 'code' => 'WG', 'name' => 'West Godavari'],
                /* ARUNACHAL PRADESH */
                ['state_id' => $ids['AR'], 'code' => 'AJ', 'name' => 'Anjaw'],
                ['state_id' => $ids['AR'], 'code' => 'CH', 'name' => 'Changlang'],
                ['state_id' => $ids['AR'], 'code' => 'UD', 'name' => 'Dibang Valley'],
                ['state_id' => $ids['AR'], 'code' => 'EK', 'name' => 'East Kameng'],
                ['state_id' => $ids['AR'], 'code' => 'ES', 'name' => 'East Siang'],
                ['state_id' => $ids['AR'], 'code' => '', 'name' => 'Kra Daadi'],
                ['state_id' => $ids['AR'], 'code' => 'KK', 'name' => 'Kurung Kumney'],
                ['state_id' => $ids['AR'], 'code' => 'EL', 'name' => 'Lohit'],
                ['state_id' => $ids['AR'], 'code' => 'LD', 'name' => 'Longding'],
                ['state_id' => $ids['AR'], 'code' => 'DV', 'name' => 'Lower Dibang Valley'],
                ['state_id' => $ids['AR'], 'code' => 'LB', 'name' => 'Lower Subansiri'],
                ['state_id' => $ids['AR'], 'code' => '', 'name' => 'Namsai'],
                ['state_id' => $ids['AR'], 'code' => 'PA', 'name' => 'Papum Pare'],
                ['state_id' => $ids['AR'], 'code' => '', 'name' => 'Siang'],
                ['state_id' => $ids['AR'], 'code' => 'TA', 'name' => 'Tawang'],
                ['state_id' => $ids['AR'], 'code' => 'TI', 'name' => 'Tirap'],
                ['state_id' => $ids['AR'], 'code' => 'US', 'name' => 'Upper Siang'],
                ['state_id' => $ids['AR'], 'code' => 'UB', 'name' => 'Upper Subansiri'],
                ['state_id' => $ids['AR'], 'code' => 'WK', 'name' => 'West Kameng'],
                ['state_id' => $ids['AR'], 'code' => 'WS', 'name' => 'West Siang'],
                /* ASSAM */
                ['state_id' => $ids['AS'], 'code' => 'BK', 'name' => 'Baksa'],
                ['state_id' => $ids['AS'], 'code' => 'BA', 'name' => 'Barpeta'],
                ['state_id' => $ids['AS'], 'code' => 'BO', 'name' => 'Bongaigaon'],
                ['state_id' => $ids['AS'], 'code' => 'CA', 'name' => 'Cachar'],
                ['state_id' => $ids['AS'], 'code' => 'CH', 'name' => 'Chirang'],
                ['state_id' => $ids['AS'], 'code' => 'DA', 'name' => 'Darrang'],
                ['state_id' => $ids['AS'], 'code' => 'DM', 'name' => 'Dhemaji'],
                ['state_id' => $ids['AS'], 'code' => 'DB', 'name' => 'Dhubri'],
                ['state_id' => $ids['AS'], 'code' => 'DI', 'name' => 'Dibrugarh'],
                ['state_id' => $ids['AS'], 'code' => 'NC', 'name' => 'Dima Hasao'],
                ['state_id' => $ids['AS'], 'code' => 'GP', 'name' => 'Goalpara'],
                ['state_id' => $ids['AS'], 'code' => 'GG', 'name' => 'Golaghat'],
                ['state_id' => $ids['AS'], 'code' => 'HA', 'name' => 'Hailakandi'],
                ['state_id' => $ids['AS'], 'code' => 'JO', 'name' => 'Jorhat'],
                ['state_id' => $ids['AS'], 'code' => 'KR', 'name' => 'Kamrup'],
                ['state_id' => $ids['AS'], 'code' => 'KM', 'name' => 'Kamrup Metropolitan'],
                ['state_id' => $ids['AS'], 'code' => 'KA', 'name' => 'Karbi Anglong'],
                ['state_id' => $ids['AS'], 'code' => 'KR', 'name' => 'Karimganj'],
                ['state_id' => $ids['AS'], 'code' => 'KK', 'name' => 'Kokrajhar'],
                ['state_id' => $ids['AS'], 'code' => 'LA', 'name' => 'Lakhimpur'],
                ['state_id' => $ids['AS'], 'code' => 'MA', 'name' => 'Marigaon'],
                ['state_id' => $ids['AS'], 'code' => 'NG', 'name' => 'Nagaon'],
                ['state_id' => $ids['AS'], 'code' => 'NL', 'name' => 'Nalbari'],
                ['state_id' => $ids['AS'], 'code' => 'SI', 'name' => 'Sivasagar'],
                ['state_id' => $ids['AS'], 'code' => 'SO', 'name' => 'Sonitpur'],
                ['state_id' => $ids['AS'], 'code' => 'TI', 'name' => 'Tinsukia'],
                ['state_id' => $ids['AS'], 'code' => 'UD', 'name' => 'Udalguri'],
                ['state_id' => $ids['AS'], 'code' => '', 'name' => 'Bishwanth'],
                ['state_id' => $ids['AS'], 'code' => '', 'name' => 'Charaideo'],
                ['state_id' => $ids['AS'], 'code' => '', 'name' => 'Hojai'],
                ['state_id' => $ids['AS'], 'code' => '', 'name' => 'South Salmara-Mankachar'],
                ['state_id' => $ids['AS'], 'code' => '', 'name' => 'West Karbi Anglong'],
                ['state_id' => $ids['AS'], 'code' => '', 'name' => 'East Kamrup'],
                ['state_id' => $ids['AS'], 'code' => '', 'name' => 'South Kamrup'],
                /* BIHAR */
                ['state_id' => $ids['BR'], 'code' => 'AR', 'name' => 'Araria'],
                ['state_id' => $ids['BR'], 'code' => 'AR', 'name' => 'Arwal'],
                ['state_id' => $ids['BR'], 'code' => 'AU', 'name' => 'Aurangabad'],
                ['state_id' => $ids['BR'], 'code' => 'BA', 'name' => 'Banka'],
                ['state_id' => $ids['BR'], 'code' => 'BE', 'name' => 'Begusarai'],
                ['state_id' => $ids['BR'], 'code' => 'BG', 'name' => 'Bhagalpur'],
                ['state_id' => $ids['BR'], 'code' => 'BJ', 'name' => 'Bhojpur'],
                ['state_id' => $ids['BR'], 'code' => 'BU', 'name' => 'Buxar'],
                ['state_id' => $ids['BR'], 'code' => 'DA', 'name' => 'Dharbanga'],
                ['state_id' => $ids['BR'], 'code' => 'EC', 'name' => 'East Champaran'],
                ['state_id' => $ids['BR'], 'code' => 'GA', 'name' => 'Gaya'],
                ['state_id' => $ids['BR'], 'code' => 'GO', 'name' => 'Gopalganj'],
                ['state_id' => $ids['BR'], 'code' => 'JA', 'name' => 'Jamui'],
                ['state_id' => $ids['BR'], 'code' => 'JE', 'name' => 'Jehanabad'],
                ['state_id' => $ids['BR'], 'code' => 'KM', 'name' => 'Kaimur'],
                ['state_id' => $ids['BR'], 'code' => 'KT', 'name' => 'Katihar'],
                ['state_id' => $ids['BR'], 'code' => 'KH', 'name' => 'Khagaria'],
                ['state_id' => $ids['BR'], 'code' => 'KI', 'name' => 'Kishanganj'],
                ['state_id' => $ids['BR'], 'code' => 'LA', 'name' => 'Lakhisarai'],
                ['state_id' => $ids['BR'], 'code' => 'MP', 'name' => 'Madhepura'],
                ['state_id' => $ids['BR'], 'code' => 'MB', 'name' => 'Madhubani'],
                ['state_id' => $ids['BR'], 'code' => 'MG', 'name' => 'Munger'],
                ['state_id' => $ids['BR'], 'code' => 'MZ', 'name' => 'Muzaffarpur'],
                ['state_id' => $ids['BR'], 'code' => 'NL', 'name' => 'Nalanda'],
                ['state_id' => $ids['BR'], 'code' => 'NW', 'name' => 'Nawada'],
                ['state_id' => $ids['BR'], 'code' => 'PA', 'name' => 'Patna'],
                ['state_id' => $ids['BR'], 'code' => 'PU', 'name' => 'Purnia'],
                ['state_id' => $ids['BR'], 'code' => 'RO', 'name' => 'Rohtas'],
                ['state_id' => $ids['BR'], 'code' => 'SH', 'name' => 'Saharsa'],
                ['state_id' => $ids['BR'], 'code' => 'SM', 'name' => 'Samastipur'],
                ['state_id' => $ids['BR'], 'code' => 'SR', 'name' => 'Saran'],
                ['state_id' => $ids['BR'], 'code' => 'SP', 'name' => 'Sheikhpura'],
                ['state_id' => $ids['BR'], 'code' => 'SO', 'name' => 'Sheohar'],
                ['state_id' => $ids['BR'], 'code' => 'ST', 'name' => 'Sitamarhi'],
                ['state_id' => $ids['BR'], 'code' => 'SW', 'name' => 'Siwan'],
                ['state_id' => $ids['BR'], 'code' => 'SU', 'name' => 'Supaul'],
                ['state_id' => $ids['BR'], 'code' => 'VA', 'name' => 'Vaishali'],
                ['state_id' => $ids['BR'], 'code' => 'WC', 'name' => 'West Champaran'],
                /* CHANDIGARH */
                ['state_id' => $ids['CH'], 'code' => 'CH', 'name' => 'Chandigarh'],
                /* CHHATTISGARH */
                ['state_id' => $ids['CG'], 'code' => '', 'name' => 'Balod'],
                ['state_id' => $ids['CG'], 'code' => '', 'name' => 'Baloda Bazar'],
                ['state_id' => $ids['CG'], 'code' => '', 'name' => 'Balrampur'],
                ['state_id' => $ids['CG'], 'code' => 'BA', 'name' => 'Bastar'],
                ['state_id' => $ids['CG'], 'code' => '', 'name' => 'Bemetara'],
                ['state_id' => $ids['CG'], 'code' => 'BJ', 'name' => 'Bijapur'],
                ['state_id' => $ids['CG'], 'code' => 'BI', 'name' => 'Bilaspur'],
                ['state_id' => $ids['CG'], 'code' => 'DA', 'name' => 'Dantewada'],
                ['state_id' => $ids['CG'], 'code' => 'DH', 'name' => 'Dhamtari'],
                ['state_id' => $ids['CG'], 'code' => 'DU', 'name' => 'Durg'],
                ['state_id' => $ids['CG'], 'code' => '', 'name' => 'Gariaband'],
                ['state_id' => $ids['CG'], 'code' => 'JC', 'name' => 'Janjgir-Champa'],
                ['state_id' => $ids['CG'], 'code' => 'JA', 'name' => 'Jashpur'],
                ['state_id' => $ids['CG'], 'code' => 'KW', 'name' => 'Kabirdham'],
                ['state_id' => $ids['CG'], 'code' => 'KK', 'name' => 'Kanker'],
                ['state_id' => $ids['CG'], 'code' => '', 'name' => 'Kondagaon'],
                ['state_id' => $ids['CG'], 'code' => 'KB', 'name' => 'Korba'],
                ['state_id' => $ids['CG'], 'code' => 'KJ', 'name' => 'Koriya'],
                ['state_id' => $ids['CG'], 'code' => 'MA', 'name' => 'Mahasamund'],
                ['state_id' => $ids['CG'], 'code' => '', 'name' => 'Mungeli'],
                ['state_id' => $ids['CG'], 'code' => 'NR', 'name' => 'Narayanpur'],
                ['state_id' => $ids['CG'], 'code' => 'RG', 'name' => 'Raigarh'],
                ['state_id' => $ids['CG'], 'code' => 'RP', 'name' => 'Raipur'],
                ['state_id' => $ids['CG'], 'code' => 'RN', 'name' => 'Rajnandgaon'],
                ['state_id' => $ids['CG'], 'code' => 'SK', 'name' => 'Sukma'],
                ['state_id' => $ids['CG'], 'code' => 'SJ', 'name' => 'Surajpur'],
                ['state_id' => $ids['CG'], 'code' => 'SJ', 'name' => 'Surguja'],
                /* DADRA AND NAGAR HAVELI */
                ['state_id' => $ids['DN'], 'code' => 'DN', 'name' => 'Dadra and Nagar Haveli'],
                /* DAMAN AND DIU */
                ['state_id' => $ids['DD'], 'code' => 'DA', 'name' => 'Daman'],
                ['state_id' => $ids['DD'], 'code' => 'DI', 'name' => 'Diu'],
                /* DELHI */
                ['state_id' => $ids['DL'], 'code' => 'CD', 'name' => 'Central Delhi'],
                ['state_id' => $ids['DL'], 'code' => 'ED', 'name' => 'East Delhi'],
                ['state_id' => $ids['DL'], 'code' => 'ND', 'name' => 'New Delhi'],
                ['state_id' => $ids['DL'], 'code' => 'NO', 'name' => 'North Delhi'],
                ['state_id' => $ids['DL'], 'code' => 'NE', 'name' => 'North East Delhi'],
                ['state_id' => $ids['DL'], 'code' => 'NW', 'name' => 'North West Delhi'],
                ['state_id' => $ids['DL'], 'code' => '', 'name' => 'Shahdara'],
                ['state_id' => $ids['DL'], 'code' => 'SD', 'name' => 'South Delhi'],
                ['state_id' => $ids['DL'], 'code' => '', 'name' => 'South East Delhi'],
                ['state_id' => $ids['DL'], 'code' => 'SW', 'name' => 'South West Delhi'],
                ['state_id' => $ids['DL'], 'code' => 'WD', 'name' => 'West Delhi'],
                /* GOA */
                ['state_id' => $ids['GA'], 'code' => 'NG', 'name' => 'North Goa'],
                ['state_id' => $ids['GA'], 'code' => 'SG', 'name' => 'South Goa'],
                /* GUJARAT */
                ['state_id' => $ids['GJ'], 'code' => 'AH', 'name' => 'Ahmedabad'],
                ['state_id' => $ids['GJ'], 'code' => 'AM', 'name' => 'Amreli'],
                ['state_id' => $ids['GJ'], 'code' => 'AN', 'name' => 'Anand'],
                ['state_id' => $ids['GJ'], 'code' => 'AR', 'name' => 'Aravalli'],
                ['state_id' => $ids['GJ'], 'code' => 'BK', 'name' => 'Banaskantha'],
                ['state_id' => $ids['GJ'], 'code' => 'BR', 'name' => 'Bharuch'],
                ['state_id' => $ids['GJ'], 'code' => 'BV', 'name' => 'Bhavnagar'],
                ['state_id' => $ids['GJ'], 'code' => '', 'name' => 'Botad'],
                ['state_id' => $ids['GJ'], 'code' => '', 'name' => 'Chhota Udaipur'],
                ['state_id' => $ids['GJ'], 'code' => 'DA', 'name' => 'Dahod'],
                ['state_id' => $ids['GJ'], 'code' => 'DG', 'name' => 'Dang'],
                ['state_id' => $ids['GJ'], 'code' => '', 'name' => 'Devbhoomi Dwaraka'],
                ['state_id' => $ids['GJ'], 'code' => 'GA', 'name' => 'Gandhinagar'],
                ['state_id' => $ids['GJ'], 'code' => '', 'name' => 'Gir Somnath'],
                ['state_id' => $ids['GJ'], 'code' => 'JA', 'name' => 'Jamnagar'],
                ['state_id' => $ids['GJ'], 'code' => 'JU', 'name' => 'Junagadh'],
                ['state_id' => $ids['GJ'], 'code' => 'KH', 'name' => 'Kheda'],
                ['state_id' => $ids['GJ'], 'code' => 'KA', 'name' => 'Kutch'],
                ['state_id' => $ids['GJ'], 'code' => 'MH', 'name' => 'Mahisagar'],
                ['state_id' => $ids['GJ'], 'code' => 'MA', 'name' => 'Mehsana'],
                ['state_id' => $ids['GJ'], 'code' => '', 'name' => 'Morbi'],
                ['state_id' => $ids['GJ'], 'code' => 'NR', 'name' => 'Narmada'],
                ['state_id' => $ids['GJ'], 'code' => 'NV', 'name' => 'Navsari'],
                ['state_id' => $ids['GJ'], 'code' => 'PM', 'name' => 'Panchmahal'],
                ['state_id' => $ids['GJ'], 'code' => 'PA', 'name' => 'Patan'],
                ['state_id' => $ids['GJ'], 'code' => 'PO', 'name' => 'Porbandar'],
                ['state_id' => $ids['GJ'], 'code' => 'RA', 'name' => 'Rajkot'],
                ['state_id' => $ids['GJ'], 'code' => 'SK', 'name' => 'Sabarkantha'],
                ['state_id' => $ids['GJ'], 'code' => 'ST', 'name' => 'Surat'],
                ['state_id' => $ids['GJ'], 'code' => 'SN', 'name' => 'Surendranagar'],
                ['state_id' => $ids['GJ'], 'code' => 'TA', 'name' => 'Tapi'],
                ['state_id' => $ids['GJ'], 'code' => 'VD', 'name' => 'Vadodara'],
                ['state_id' => $ids['GJ'], 'code' => 'VL', 'name' => 'Valsad'],
                /* HARYANA */
                ['state_id' => $ids['HR'], 'code' => 'AM', 'name' => 'Ambala'],
                ['state_id' => $ids['HR'], 'code' => 'BH', 'name' => 'Bhiwani'],
                ['state_id' => $ids['HR'], 'code' => 'FR', 'name' => 'Faridabad'],
                ['state_id' => $ids['HR'], 'code' => 'FT', 'name' => 'Fatehabad'],
                ['state_id' => $ids['HR'], 'code' => 'GU', 'name' => 'Gurgaon'],
                ['state_id' => $ids['HR'], 'code' => 'HI', 'name' => 'Hissar'],
                ['state_id' => $ids['HR'], 'code' => 'JH', 'name' => 'Jhajjar'],
                ['state_id' => $ids['HR'], 'code' => 'JI', 'name' => 'Jind'],
                ['state_id' => $ids['HR'], 'code' => 'KT', 'name' => 'Kaithal'],
                ['state_id' => $ids['HR'], 'code' => 'KR', 'name' => 'Karnal'],
                ['state_id' => $ids['HR'], 'code' => 'KU', 'name' => 'Kurukshetra'],
                ['state_id' => $ids['HR'], 'code' => 'MA', 'name' => 'Mahendragarh'],
                ['state_id' => $ids['HR'], 'code' => 'MW', 'name' => 'Mewat'],
                ['state_id' => $ids['HR'], 'code' => 'PW', 'name' => 'Palwal'],
                ['state_id' => $ids['HR'], 'code' => 'PK', 'name' => 'Panchkula'],
                ['state_id' => $ids['HR'], 'code' => 'PP', 'name' => 'Panipat'],
                ['state_id' => $ids['HR'], 'code' => 'RE', 'name' => 'Rewari'],
                ['state_id' => $ids['HR'], 'code' => 'RO', 'name' => 'Rohtak'],
                ['state_id' => $ids['HR'], 'code' => 'SI', 'name' => 'Sirsa'],
                ['state_id' => $ids['HR'], 'code' => 'SNP', 'name' => 'Sonipat'],
                ['state_id' => $ids['HR'], 'code' => 'YN', 'name' => 'Yamuna Nagar'],
                /* HIMACHAL PRADESH */
                ['state_id' => $ids['HP'], 'code' => 'BI', 'name' => 'Bilaspur'],
                ['state_id' => $ids['HP'], 'code' => 'CH', 'name' => 'Chamba'],
                ['state_id' => $ids['HP'], 'code' => 'HA', 'name' => 'Hamirpur'],
                ['state_id' => $ids['HP'], 'code' => 'KA', 'name' => 'Kangra'],
                ['state_id' => $ids['HP'], 'code' => 'KI', 'name' => 'Kinnaur'],
                ['state_id' => $ids['HP'], 'code' => 'KU', 'name' => 'Kullu'],
                ['state_id' => $ids['HP'], 'code' => 'LS', 'name' => 'Lahaul and Spiti'],
                ['state_id' => $ids['HP'], 'code' => 'MA', 'name' => 'Mandi'],
                ['state_id' => $ids['HP'], 'code' => 'SH', 'name' => 'Shimla'],
                ['state_id' => $ids['HP'], 'code' => 'SI', 'name' => 'Sirmaur'],
                ['state_id' => $ids['HP'], 'code' => 'SO', 'name' => 'Solan'],
                ['state_id' => $ids['HP'], 'code' => 'UNA', 'name' => 'Una'],
                /* JAMMU AND KASHMIR */
                ['state_id' => $ids['JK'], 'code' => 'AN', 'name' => 'Anantnag'],
                ['state_id' => $ids['JK'], 'code' => 'BPR', 'name' => 'Bandipora'],
                ['state_id' => $ids['JK'], 'code' => 'BR', 'name' => 'Baramulla'],
                ['state_id' => $ids['JK'], 'code' => 'BD', 'name' => 'Badgam'],
                ['state_id' => $ids['JK'], 'code' => 'DO', 'name' => 'Doda'],
                ['state_id' => $ids['JK'], 'code' => 'GB', 'name' => 'Ganderbal'],
                ['state_id' => $ids['JK'], 'code' => 'JA', 'name' => 'Jammu'],
                ['state_id' => $ids['JK'], 'code' => 'KR', 'name' => 'Kargil'],
                ['state_id' => $ids['JK'], 'code' => 'KT', 'name' => 'Kathua'],
                ['state_id' => $ids['JK'], 'code' => 'KW', 'name' => 'Kishtwar'],
                ['state_id' => $ids['JK'], 'code' => 'KG', 'name' => 'Kulgam'],
                ['state_id' => $ids['JK'], 'code' => 'KU', 'name' => 'Kupwara'],
                ['state_id' => $ids['JK'], 'code' => 'LE', 'name' => 'Leh'],
                ['state_id' => $ids['JK'], 'code' => 'PO', 'name' => 'Poonch'],
                ['state_id' => $ids['JK'], 'code' => 'PU', 'name' => 'Pulwama'],
                ['state_id' => $ids['JK'], 'code' => 'RA', 'name' => 'Rajouri'],
                ['state_id' => $ids['JK'], 'code' => 'RB', 'name' => 'Ramban'],
                ['state_id' => $ids['JK'], 'code' => 'RS', 'name' => 'Reasi'],
                ['state_id' => $ids['JK'], 'code' => 'SB', 'name' => 'Samba'],
                ['state_id' => $ids['JK'], 'code' => 'SH', 'name' => 'Shopian'],
                ['state_id' => $ids['JK'], 'code' => 'SR', 'name' => 'Srinagar'],
                ['state_id' => $ids['JK'], 'code' => 'UD', 'name' => 'Udhampur'],
                /* JHARKHAND */
                ['state_id' => $ids['JH'], 'code' => 'BO', 'name' => 'Bokaro'],
                ['state_id' => $ids['JH'], 'code' => 'CH', 'name' => 'Chatra'],
                ['state_id' => $ids['JH'], 'code' => 'DE', 'name' => 'Deoghar'],
                ['state_id' => $ids['JH'], 'code' => 'DH', 'name' => 'Dhanbad'],
                ['state_id' => $ids['JH'], 'code' => 'DU', 'name' => 'Dumka'],
                ['state_id' => $ids['JH'], 'code' => 'ES', 'name' => 'East Singhbhum'],
                ['state_id' => $ids['JH'], 'code' => 'GA', 'name' => 'Garhwa'],
                ['state_id' => $ids['JH'], 'code' => 'GI', 'name' => 'Giridih'],
                ['state_id' => $ids['JH'], 'code' => 'GO', 'name' => 'Godda'],
                ['state_id' => $ids['JH'], 'code' => 'GU', 'name' => 'Gumla'],
                ['state_id' => $ids['JH'], 'code' => 'HA', 'name' => 'Hazaribag'],
                ['state_id' => $ids['JH'], 'code' => 'JA', 'name' => 'Jamtara'],
                ['state_id' => $ids['JH'], 'code' => 'KH', 'name' => 'Khunti'],
                ['state_id' => $ids['JH'], 'code' => 'KO', 'name' => 'Koderma'],
                ['state_id' => $ids['JH'], 'code' => 'LA', 'name' => 'Latehar'],
                ['state_id' => $ids['JH'], 'code' => 'LO', 'name' => 'Lohardaga'],
                ['state_id' => $ids['JH'], 'code' => 'PK', 'name' => 'Pakur'],
                ['state_id' => $ids['JH'], 'code' => 'PL', 'name' => 'Palamu'],
                ['state_id' => $ids['JH'], 'code' => 'RM', 'name' => 'Ramgarh'],
                ['state_id' => $ids['JH'], 'code' => 'RA', 'name' => 'Ranchi'],
                ['state_id' => $ids['JH'], 'code' => 'SA', 'name' => 'Sahibganj'],
                ['state_id' => $ids['JH'], 'code' => 'SK', 'name' => 'Seraikela Kharsawan'],
                ['state_id' => $ids['JH'], 'code' => 'SI', 'name' => 'Simdega'],
                ['state_id' => $ids['JH'], 'code' => 'WS', 'name' => 'West Singhbhum'],
                /* KARNATAKA */
                ['state_id' => $ids['KA'], 'code' => 'BK', 'name' => 'Bagalkot'],
                ['state_id' => $ids['KA'], 'code' => 'BL', 'name' => 'Bellary'],
                ['state_id' => $ids['KA'], 'code' => 'BG', 'name' => 'Belgaum'],
                ['state_id' => $ids['KA'], 'code' => 'BR', 'name' => 'Bangalore Rural'],
                ['state_id' => $ids['KA'], 'code' => 'BN', 'name' => 'Bangalore Urban'],
                ['state_id' => $ids['KA'], 'code' => 'BD', 'name' => 'Bidar'],
                ['state_id' => $ids['KA'], 'code' => 'CJ', 'name' => 'Chamarajnagar'],
                ['state_id' => $ids['KA'], 'code' => 'CK', 'name' => 'Chikkaballapur'],
                ['state_id' => $ids['KA'], 'code' => 'CK', 'name' => 'Chikkamagaluru'],
                ['state_id' => $ids['KA'], 'code' => 'CT', 'name' => 'Chitradurga'],
                ['state_id' => $ids['KA'], 'code' => 'DK', 'name' => 'Dakshina Kannada'],
                ['state_id' => $ids['KA'], 'code' => 'DA', 'name' => 'Davanagere'],
                ['state_id' => $ids['KA'], 'code' => 'DH', 'name' => 'Dharwad'],
                ['state_id' => $ids['KA'], 'code' => 'GA', 'name' => 'Gadag'],
                ['state_id' => $ids['KA'], 'code' => 'HS', 'name' => 'Hassan'],
                ['state_id' => $ids['KA'], 'code' => 'HV', 'name' => 'Haveri District'],
                ['state_id' => $ids['KA'], 'code' => 'GU', 'name' => 'Gulbarga'],
                ['state_id' => $ids['KA'], 'code' => 'KD', 'name' => 'Kodagu'],
                ['state_id' => $ids['KA'], 'code' => 'KL', 'name' => 'Kolar'],
                ['state_id' => $ids['KA'], 'code' => 'KP', 'name' => 'Koppal'],
                ['state_id' => $ids['KA'], 'code' => 'MA', 'name' => 'Mandya'],
                ['state_id' => $ids['KA'], 'code' => 'MY', 'name' => 'Mysore'],
                ['state_id' => $ids['KA'], 'code' => 'RA', 'name' => 'Raichur'],
                ['state_id' => $ids['KA'], 'code' => 'RM', 'name' => 'Ramanagara'],
                ['state_id' => $ids['KA'], 'code' => 'SH', 'name' => 'Shimoga'],
                ['state_id' => $ids['KA'], 'code' => 'TU', 'name' => 'Tumkur'],
                ['state_id' => $ids['KA'], 'code' => 'UD', 'name' => 'Udupi'],
                ['state_id' => $ids['KA'], 'code' => 'UK', 'name' => 'Uttara Kannada'],
                ['state_id' => $ids['KA'], 'code' => 'BJ', 'name' => 'Vijayapura'],
                ['state_id' => $ids['KA'], 'code' => 'YG', 'name' => 'Yadgir'],
                /* KERALA */
                ['state_id' => $ids['KL'], 'code' => 'AL', 'name' => 'Alappuzha'],
                ['state_id' => $ids['KL'], 'code' => 'ER', 'name' => 'Ernakulam'],
                ['state_id' => $ids['KL'], 'code' => 'ID', 'name' => 'Idukki'],
                ['state_id' => $ids['KL'], 'code' => 'KN', 'name' => 'Kannur'],
                ['state_id' => $ids['KL'], 'code' => 'KS', 'name' => 'Kasargod'],
                ['state_id' => $ids['KL'], 'code' => 'KL', 'name' => 'Kollam'],
                ['state_id' => $ids['KL'], 'code' => 'KT', 'name' => 'Kottayam'],
                ['state_id' => $ids['KL'], 'code' => 'KZ', 'name' => 'Kozhikode'],
                ['state_id' => $ids['KL'], 'code' => 'MA', 'name' => 'Malappuram'],
                ['state_id' => $ids['KL'], 'code' => 'PL', 'name' => 'Palakkad'],
                ['state_id' => $ids['KL'], 'code' => 'PT', 'name' => 'Pathanamthitta'],
                ['state_id' => $ids['KL'], 'code' => 'TS', 'name' => 'Thrissur'],
                ['state_id' => $ids['KL'], 'code' => 'TV', 'name' => 'Thiruvananthapuram'],
                ['state_id' => $ids['KL'], 'code' => 'WA', 'name' => 'Wayanad'],
                /* LAKSHADWEEP */
                ['state_id' => $ids['LD'], 'code' => 'LD', 'name' => 'Lakshadweep'],
                /* MADHYA PRADESH */
                ['state_id' => $ids['MP'], 'code' => 'AG', 'name' => 'Agar Malwa'],
                ['state_id' => $ids['MP'], 'code' => 'AL', 'name' => 'Alirajpur'],
                ['state_id' => $ids['MP'], 'code' => 'AP', 'name' => 'Anuppur'],
                ['state_id' => $ids['MP'], 'code' => 'AS', 'name' => 'Ashok Nagar'],
                ['state_id' => $ids['MP'], 'code' => 'BL', 'name' => 'Balaghat'],
                ['state_id' => $ids['MP'], 'code' => 'BR', 'name' => 'Barwani'],
                ['state_id' => $ids['MP'], 'code' => 'BE', 'name' => 'Betul'],
                ['state_id' => $ids['MP'], 'code' => 'BD', 'name' => 'Bhind'],
                ['state_id' => $ids['MP'], 'code' => 'BP', 'name' => 'Bhopal'],
                ['state_id' => $ids['MP'], 'code' => 'BU', 'name' => 'Burhanpur'],
                ['state_id' => $ids['MP'], 'code' => 'CT', 'name' => 'Chhatarpur'],
                ['state_id' => $ids['MP'], 'code' => 'CN', 'name' => 'Chhindwara'],
                ['state_id' => $ids['MP'], 'code' => 'DM', 'name' => 'Damoh'],
                ['state_id' => $ids['MP'], 'code' => 'DT', 'name' => 'Datia'],
                ['state_id' => $ids['MP'], 'code' => 'DE', 'name' => 'Dewas'],
                ['state_id' => $ids['MP'], 'code' => 'DH', 'name' => 'Dhar'],
                ['state_id' => $ids['MP'], 'code' => 'DI', 'name' => 'Dindori'],
                ['state_id' => $ids['MP'], 'code' => 'GU', 'name' => 'Guna'],
                ['state_id' => $ids['MP'], 'code' => 'GW', 'name' => 'Gwalior'],
                ['state_id' => $ids['MP'], 'code' => 'HA', 'name' => 'Harda'],
                ['state_id' => $ids['MP'], 'code' => 'HO', 'name' => 'Hoshangabad'],
                ['state_id' => $ids['MP'], 'code' => 'IN', 'name' => 'Indore'],
                ['state_id' => $ids['MP'], 'code' => 'JA', 'name' => 'Jabalpur'],
                ['state_id' => $ids['MP'], 'code' => 'JH', 'name' => 'Jhabua'],
                ['state_id' => $ids['MP'], 'code' => 'KA', 'name' => 'Katni'],
                ['state_id' => $ids['MP'], 'code' => 'EN', 'name' => 'Khandwa(East Nimar)'],
                ['state_id' => $ids['MP'], 'code' => 'WN', 'name' => 'Khargone(West Nimar)'],
                ['state_id' => $ids['MP'], 'code' => 'ML', 'name' => 'Mandla'],
                ['state_id' => $ids['MP'], 'code' => 'MS', 'name' => 'Mandsaur'],
                ['state_id' => $ids['MP'], 'code' => 'MO', 'name' => 'Morena'],
                ['state_id' => $ids['MP'], 'code' => 'NA', 'name' => 'Narsinghpur'],
                ['state_id' => $ids['MP'], 'code' => 'NE', 'name' => 'Neemuch'],
                ['state_id' => $ids['MP'], 'code' => 'PA', 'name' => 'Panna'],
                ['state_id' => $ids['MP'], 'code' => 'RS', 'name' => 'Raisen'],
                ['state_id' => $ids['MP'], 'code' => 'RG', 'name' => 'Rajgarh'],
                ['state_id' => $ids['MP'], 'code' => 'RL', 'name' => 'Ratlam'],
                ['state_id' => $ids['MP'], 'code' => 'RE', 'name' => 'Rewa'],
                ['state_id' => $ids['MP'], 'code' => 'SG', 'name' => 'Sagar'],
                ['state_id' => $ids['MP'], 'code' => 'ST', 'name' => 'Satna'],
                ['state_id' => $ids['MP'], 'code' => 'SR', 'name' => 'Sehore'],
                ['state_id' => $ids['MP'], 'code' => 'SO', 'name' => 'Seoni'],
                ['state_id' => $ids['MP'], 'code' => 'SH', 'name' => 'Shahdol'],
                ['state_id' => $ids['MP'], 'code' => 'SJ', 'name' => 'Shajapur'],
                ['state_id' => $ids['MP'], 'code' => 'SP', 'name' => 'Sheopur'],
                ['state_id' => $ids['MP'], 'code' => 'SV', 'name' => 'Shivpuri'],
                ['state_id' => $ids['MP'], 'code' => 'SI', 'name' => 'Sidhi'],
                ['state_id' => $ids['MP'], 'code' => 'SN', 'name' => 'Singrauli'],
                ['state_id' => $ids['MP'], 'code' => 'TI', 'name' => 'Tikamgarh'],
                ['state_id' => $ids['MP'], 'code' => 'UJ', 'name' => 'Ujjain'],
                ['state_id' => $ids['MP'], 'code' => 'UM', 'name' => 'Umaria'],
                ['state_id' => $ids['MP'], 'code' => 'VI', 'name' => 'Vidisha'],
                /* MAHARASHTRA */
                ['state_id' => $ids['MH'], 'code' => 'AH', 'name' => 'Ahmednagar'],
                ['state_id' => $ids['MH'], 'code' => 'AK', 'name' => 'Akola'],
                ['state_id' => $ids['MH'], 'code' => 'AM', 'name' => 'Amravati'],
                ['state_id' => $ids['MH'], 'code' => 'AU', 'name' => 'Aurangabad'],
                ['state_id' => $ids['MH'], 'code' => 'BI', 'name' => 'Beed'],
                ['state_id' => $ids['MH'], 'code' => 'BH', 'name' => 'Bhandara'],
                ['state_id' => $ids['MH'], 'code' => 'BU', 'name' => 'Buldhana'],
                ['state_id' => $ids['MH'], 'code' => 'CH', 'name' => 'Chandrapur'],
                ['state_id' => $ids['MH'], 'code' => 'DH', 'name' => 'Dhule'],
                ['state_id' => $ids['MH'], 'code' => 'GA', 'name' => 'Gadchiroli'],
                ['state_id' => $ids['MH'], 'code' => 'GO', 'name' => 'Gondia'],
                ['state_id' => $ids['MH'], 'code' => 'HI', 'name' => 'Hingoli'],
                ['state_id' => $ids['MH'], 'code' => 'JG', 'name' => 'Jalgaon'],
                ['state_id' => $ids['MH'], 'code' => 'JN', 'name' => 'Jalna'],
                ['state_id' => $ids['MH'], 'code' => 'KO', 'name' => 'Kolhapur'],
                ['state_id' => $ids['MH'], 'code' => 'LA', 'name' => 'Latur'],
                ['state_id' => $ids['MH'], 'code' => 'MC', 'name' => 'Mumbai City'],
                ['state_id' => $ids['MH'], 'code' => 'MU', 'name' => 'Mumbai Suburban'],
                ['state_id' => $ids['MH'], 'code' => 'ND', 'name' => 'Nanded'],
                ['state_id' => $ids['MH'], 'code' => 'NB', 'name' => 'Nandurbar'],
                ['state_id' => $ids['MH'], 'code' => 'NG', 'name' => 'Nagpur'],
                ['state_id' => $ids['MH'], 'code' => 'NS', 'name' => 'Nashik'],
                ['state_id' => $ids['MH'], 'code' => 'OS', 'name' => 'Osmanabad'],
                ['state_id' => $ids['MH'], 'code' => '', 'name' => 'Palghar'],
                ['state_id' => $ids['MH'], 'code' => 'PA', 'name' => 'Parbhani'],
                ['state_id' => $ids['MH'], 'code' => 'PU', 'name' => 'Pune'],
                ['state_id' => $ids['MH'], 'code' => 'RG', 'name' => 'Rajgad'],
                ['state_id' => $ids['MH'], 'code' => 'RT', 'name' => 'Ratnagiri'],
                ['state_id' => $ids['MH'], 'code' => 'SN', 'name' => 'Sangli'],
                ['state_id' => $ids['MH'], 'code' => 'ST', 'name' => 'Satara'],
                ['state_id' => $ids['MH'], 'code' => 'SI', 'name' => 'Sindhudurg'],
                ['state_id' => $ids['MH'], 'code' => 'SO', 'name' => 'Solapur'],
                ['state_id' => $ids['MH'], 'code' => 'TH', 'name' => 'Thane'],
                ['state_id' => $ids['MH'], 'code' => 'WR', 'name' => 'Wardha'],
                ['state_id' => $ids['MH'], 'code' => 'WS', 'name' => 'Washim'],
                ['state_id' => $ids['MH'], 'code' => 'YA', 'name' => 'Yavatmal'],
                /* MANIPUR */
                ['state_id' => $ids['MN'], 'code' => 'BI', 'name' => 'Bishnupur'],
                ['state_id' => $ids['MN'], 'code' => 'CC', 'name' => 'Churachandpur'],
                ['state_id' => $ids['MN'], 'code' => 'CD', 'name' => 'Chandel'],
                ['state_id' => $ids['MN'], 'code' => 'EI', 'name' => 'Imphal East'],
                ['state_id' => $ids['MN'], 'code' => 'SE', 'name' => 'Senapati'],
                ['state_id' => $ids['MN'], 'code' => 'TA', 'name' => 'Tamenglong'],
                ['state_id' => $ids['MN'], 'code' => 'TH', 'name' => 'Thoubal'],
                ['state_id' => $ids['MN'], 'code' => 'UK', 'name' => 'Ukhrul'],
                ['state_id' => $ids['MN'], 'code' => 'WI', 'name' => 'Imphal West'],
                /* MEGHALAYA */
                ['state_id' => $ids['ML'], 'code' => 'EG', 'name' => 'East Garo Hills'],
                ['state_id' => $ids['ML'], 'code' => 'EK', 'name' => 'East Khasi Hills'],
                ['state_id' => $ids['ML'], 'code' => '', 'name' => 'East Jaintia Hills'],
                ['state_id' => $ids['ML'], 'code' => '', 'name' => 'East Garo Hills'],
                ['state_id' => $ids['ML'], 'code' => 'RB', 'name' => 'Ri Bhoi'],
                ['state_id' => $ids['ML'], 'code' => 'SG', 'name' => 'South Garo Hills'],
                ['state_id' => $ids['ML'], 'code' => '', 'name' => 'South West Garo Hills'],
                ['state_id' => $ids['ML'], 'code' => '', 'name' => 'South West Khasi Hills'],
                ['state_id' => $ids['ML'], 'code' => 'WG', 'name' => 'West Jaintia Hills'],
                ['state_id' => $ids['ML'], 'code' => 'WG', 'name' => 'West Garo Hills'],
                ['state_id' => $ids['ML'], 'code' => 'WK', 'name' => 'West Khasi Hills'],
                /* MIZORAM */
                ['state_id' => $ids['MZ'], 'code' => 'AI', 'name' => 'Aizawl'],
                ['state_id' => $ids['MZ'], 'code' => 'CH', 'name' => 'Champhai'],
                ['state_id' => $ids['MZ'], 'code' => 'KO', 'name' => 'Kolasib'],
                ['state_id' => $ids['MZ'], 'code' => 'LA', 'name' => 'Lawngtlai'],
                ['state_id' => $ids['MZ'], 'code' => 'LU', 'name' => 'Lunglei'],
                ['state_id' => $ids['MZ'], 'code' => 'MA', 'name' => 'Mamit'],
                ['state_id' => $ids['MZ'], 'code' => 'SA', 'name' => 'Saiha'],
                ['state_id' => $ids['MZ'], 'code' => 'SE', 'name' => 'Serchhip'],
                /* NAGALAND */
                ['state_id' => $ids['NL'], 'code' => 'DI', 'name' => 'Dimapur'],
                ['state_id' => $ids['NL'], 'code' => 'KI', 'name' => 'Kiphire'],
                ['state_id' => $ids['NL'], 'code' => 'KO', 'name' => 'Kohima'],
                ['state_id' => $ids['NL'], 'code' => 'LO', 'name' => 'Longleng'],
                ['state_id' => $ids['NL'], 'code' => 'MK', 'name' => 'Mokokchung'],
                ['state_id' => $ids['NL'], 'code' => 'MN', 'name' => 'Mon'],
                ['state_id' => $ids['NL'], 'code' => 'PE', 'name' => 'Peren'],
                ['state_id' => $ids['NL'], 'code' => 'PH', 'name' => 'Phek'],
                ['state_id' => $ids['NL'], 'code' => 'TU', 'name' => 'Tuensang'],
                ['state_id' => $ids['NL'], 'code' => 'WO', 'name' => 'Wokha'],
                ['state_id' => $ids['NL'], 'code' => 'ZU', 'name' => 'Zunheboto'],
                /* ODISHA */
                ['state_id' => $ids['OD'], 'code' => 'AN', 'name' => 'Angul'],
                ['state_id' => $ids['OD'], 'code' => 'BD', 'name' => 'Boudh(Bauda)'],
                ['state_id' => $ids['OD'], 'code' => 'BH', 'name' => 'Bhadrak'],
                ['state_id' => $ids['OD'], 'code' => 'BL', 'name' => 'Balangir'],
                ['state_id' => $ids['OD'], 'code' => 'BR', 'name' => 'Bargarh(Baragarh)'],
                ['state_id' => $ids['OD'], 'code' => 'BW', 'name' => 'Balasore'],
                ['state_id' => $ids['OD'], 'code' => 'CU', 'name' => 'Cuttack'],
                ['state_id' => $ids['OD'], 'code' => 'DE', 'name' => 'Debagarh'],
                ['state_id' => $ids['OD'], 'code' => 'DH', 'name' => 'Dhenkanal'],
                ['state_id' => $ids['OD'], 'code' => 'GN', 'name' => 'Ganjam'],
                ['state_id' => $ids['OD'], 'code' => 'GP', 'name' => 'Gajapati'],
                ['state_id' => $ids['OD'], 'code' => 'JH', 'name' => 'Jharsuguda'],
                ['state_id' => $ids['OD'], 'code' => 'JP', 'name' => 'Jajpur'],
                ['state_id' => $ids['OD'], 'code' => 'JS', 'name' => 'Jagatsinghpur'],
                ['state_id' => $ids['OD'], 'code' => 'KH', 'name' => 'Khordha'],
                ['state_id' => $ids['OD'], 'code' => 'KJ', 'name' => 'Kendujhar(Keonjhar)'],
                ['state_id' => $ids['OD'], 'code' => 'KL', 'name' => 'Kalahandi'],
                ['state_id' => $ids['OD'], 'code' => 'KN', 'name' => 'Kandhamal'],
                ['state_id' => $ids['OD'], 'code' => 'KO', 'name' => 'Koraput'],
                ['state_id' => $ids['OD'], 'code' => 'KP', 'name' => 'Kendrapara'],
                ['state_id' => $ids['OD'], 'code' => 'ML', 'name' => 'Malkangiri'],
                ['state_id' => $ids['OD'], 'code' => 'MY', 'name' => 'Mayurbhanj'],
                ['state_id' => $ids['OD'], 'code' => 'NB', 'name' => 'Nabarangpur'],
                ['state_id' => $ids['OD'], 'code' => 'NU', 'name' => 'Nuapada'],
                ['state_id' => $ids['OD'], 'code' => 'NY', 'name' => 'Nayagarh'],
                ['state_id' => $ids['OD'], 'code' => 'PU', 'name' => 'Puri'],
                ['state_id' => $ids['OD'], 'code' => 'RA', 'name' => 'Rayagada'],
                ['state_id' => $ids['OD'], 'code' => 'SA', 'name' => 'Sambalpur'],
                ['state_id' => $ids['OD'], 'code' => 'SO', 'name' => 'Subarnapur(Sonepur)'],
                ['state_id' => $ids['OD'], 'code' => 'SU', 'name' => 'Sundargarh'],
                /* PUDUCHERRY (Pondicherry) */
                ['state_id' => $ids['PY'], 'code' => 'KA', 'name' => 'Karaikal'],
                ['state_id' => $ids['PY'], 'code' => 'MA', 'name' => 'Mahe'],
                ['state_id' => $ids['PY'], 'code' => 'PO', 'name' => 'Pondicherry'],
                ['state_id' => $ids['PY'], 'code' => 'YA', 'name' => 'Yanam'],
                /* PUNJAB */
                ['state_id' => $ids['PB'], 'code' => 'AM', 'name' => 'Amritsar'],
                ['state_id' => $ids['PB'], 'code' => 'BNL', 'name' => 'Barnala'],
                ['state_id' => $ids['PB'], 'code' => 'BA', 'name' => 'Bathinda'],
                ['state_id' => $ids['PB'], 'code' => 'FI', 'name' => 'Firozpur'],
                ['state_id' => $ids['PB'], 'code' => 'FR', 'name' => 'Faridkot'],
                ['state_id' => $ids['PB'], 'code' => 'FT', 'name' => 'Fatehgarh Sahib'],
                ['state_id' => $ids['PB'], 'code' => 'FA', 'name' => 'Fazilka'],
                ['state_id' => $ids['PB'], 'code' => 'GU', 'name' => 'Gurdaspur'],
                ['state_id' => $ids['PB'], 'code' => 'HO', 'name' => 'Hoshiarpur'],
                ['state_id' => $ids['PB'], 'code' => 'JA', 'name' => 'Jalandhar'],
                ['state_id' => $ids['PB'], 'code' => 'KA', 'name' => 'Kapurthala'],
                ['state_id' => $ids['PB'], 'code' => 'LU', 'name' => 'Ludhiana'],
                ['state_id' => $ids['PB'], 'code' => 'MA', 'name' => 'Mansa'],
                ['state_id' => $ids['PB'], 'code' => 'MO', 'name' => 'Moga'],
                ['state_id' => $ids['PB'], 'code' => 'MU', 'name' => 'Sri Muktsar Sahib'],
                ['state_id' => $ids['PB'], 'code' => 'PA', 'name' => 'Pathankot'],
                ['state_id' => $ids['PB'], 'code' => 'PA', 'name' => 'Patiala'],
                ['state_id' => $ids['PB'], 'code' => 'RU', 'name' => 'Rupnagar'],
                ['state_id' => $ids['PB'], 'code' => 'SAS', 'name' => 'Sahibzada Ajit Singh Nagar'],
                ['state_id' => $ids['PB'], 'code' => 'SA', 'name' => 'Sangrur'],
                ['state_id' => $ids['PB'], 'code' => 'PB', 'name' => 'Shahid Bhagat Singh Nagar'],
                ['state_id' => $ids['PB'], 'code' => 'TT', 'name' => 'Tarn Taran'],
                /* RAJASTHAN */
                ['state_id' => $ids['RJ'], 'code' => 'AJ', 'name' => 'Ajmer'],
                ['state_id' => $ids['RJ'], 'code' => 'AL', 'name' => 'Alwar'],
                ['state_id' => $ids['RJ'], 'code' => 'BI', 'name' => 'Bikaner'],
                ['state_id' => $ids['RJ'], 'code' => 'BM', 'name' => 'Barmer'],
                ['state_id' => $ids['RJ'], 'code' => 'BN', 'name' => 'Banswara'],
                ['state_id' => $ids['RJ'], 'code' => 'BP', 'name' => 'Bharatpur'],
                ['state_id' => $ids['RJ'], 'code' => 'BR', 'name' => 'Baran'],
                ['state_id' => $ids['RJ'], 'code' => 'BU', 'name' => 'Bundi'],
                ['state_id' => $ids['RJ'], 'code' => 'BW', 'name' => 'Bhilwara'],
                ['state_id' => $ids['RJ'], 'code' => 'CR', 'name' => 'Churu'],
                ['state_id' => $ids['RJ'], 'code' => 'CT', 'name' => 'Chittorgarh'],
                ['state_id' => $ids['RJ'], 'code' => 'DA', 'name' => 'Dausa'],
                ['state_id' => $ids['RJ'], 'code' => 'DH', 'name' => 'Dholpur'],
                ['state_id' => $ids['RJ'], 'code' => 'DU', 'name' => 'Dungapur'],
                ['state_id' => $ids['RJ'], 'code' => 'GA', 'name' => 'Ganganagar'],
                ['state_id' => $ids['RJ'], 'code' => 'HA', 'name' => 'Hanumangarh'],
                ['state_id' => $ids['RJ'], 'code' => 'JJ', 'name' => 'Jhunjhunu'],
                ['state_id' => $ids['RJ'], 'code' => 'JL', 'name' => 'Jalore'],
                ['state_id' => $ids['RJ'], 'code' => 'JO', 'name' => 'Jodhpur'],
                ['state_id' => $ids['RJ'], 'code' => 'JP', 'name' => 'Jaipur'],
                ['state_id' => $ids['RJ'], 'code' => 'JS', 'name' => 'Jaisalmer'],
                ['state_id' => $ids['RJ'], 'code' => 'JW', 'name' => 'Jhalawar'],
                ['state_id' => $ids['RJ'], 'code' => 'KA', 'name' => 'Karauli'],
                ['state_id' => $ids['RJ'], 'code' => 'KO', 'name' => 'Kota'],
                ['state_id' => $ids['RJ'], 'code' => 'NA', 'name' => 'Nagaur'],
                ['state_id' => $ids['RJ'], 'code' => 'PA', 'name' => 'Pali'],
                ['state_id' => $ids['RJ'], 'code' => 'PG', 'name' => 'Pratapgarh'],
                ['state_id' => $ids['RJ'], 'code' => 'RA', 'name' => 'Rajsamand'],
                ['state_id' => $ids['RJ'], 'code' => 'SK', 'name' => 'Sikar'],
                ['state_id' => $ids['RJ'], 'code' => 'SM', 'name' => 'Sawai Madhopur'],
                ['state_id' => $ids['RJ'], 'code' => 'SR', 'name' => 'Sirohi'],
                ['state_id' => $ids['RJ'], 'code' => 'TO', 'name' => 'Tonk'],
                ['state_id' => $ids['RJ'], 'code' => 'UD', 'name' => 'Udaipur'],
                /* SIKKIM */
                ['state_id' => $ids['SK'], 'code' => 'ES', 'name' => 'East Sikkim'],
                ['state_id' => $ids['SK'], 'code' => 'NS', 'name' => 'North Sikkim'],
                ['state_id' => $ids['SK'], 'code' => 'SS', 'name' => 'South Sikkim'],
                ['state_id' => $ids['SK'], 'code' => 'WS', 'name' => 'West Sikkim'],
                /* TAMIL NADU */
                ['state_id' => $ids['TN'], 'code' => 'AY', 'name' => 'Ariyalur'],
                ['state_id' => $ids['TN'], 'code' => 'CH', 'name' => 'Chennai'],
                ['state_id' => $ids['TN'], 'code' => 'CO', 'name' => 'Coimbatore'],
                ['state_id' => $ids['TN'], 'code' => 'CU', 'name' => 'Cuddalore'],
                ['state_id' => $ids['TN'], 'code' => 'DH', 'name' => 'Dharmapuri'],
                ['state_id' => $ids['TN'], 'code' => 'DI', 'name' => 'Dindigul'],
                ['state_id' => $ids['TN'], 'code' => 'ER', 'name' => 'Erode'],
                ['state_id' => $ids['TN'], 'code' => 'KC', 'name' => 'Kanchipuram'],
                ['state_id' => $ids['TN'], 'code' => 'KK', 'name' => 'Kanyakumari'],
                ['state_id' => $ids['TN'], 'code' => 'KA', 'name' => 'Karur'],
                ['state_id' => $ids['TN'], 'code' => 'KR', 'name' => 'Krishnagiri'],
                ['state_id' => $ids['TN'], 'code' => 'MA', 'name' => 'Madurai'],
                ['state_id' => $ids['TN'], 'code' => 'NG', 'name' => 'Nagapattinam'],
                ['state_id' => $ids['TN'], 'code' => 'NI', 'name' => 'Nilgiris'],
                ['state_id' => $ids['TN'], 'code' => 'NM', 'name' => 'Namakkal'],
                ['state_id' => $ids['TN'], 'code' => 'PE', 'name' => 'Perambalur'],
                ['state_id' => $ids['TN'], 'code' => 'PU', 'name' => 'Pudukkottai'],
                ['state_id' => $ids['TN'], 'code' => 'RA', 'name' => 'Ramanathapuram'],
                ['state_id' => $ids['TN'], 'code' => 'SA', 'name' => 'Salem'],
                ['state_id' => $ids['TN'], 'code' => 'SI', 'name' => 'Sivaganga'],
                ['state_id' => $ids['TN'], 'code' => 'TP', 'name' => 'Tirupur'],
                ['state_id' => $ids['TN'], 'code' => 'TC', 'name' => 'Tiruchirappalli'],
                ['state_id' => $ids['TN'], 'code' => 'TH', 'name' => 'Theni'],
                ['state_id' => $ids['TN'], 'code' => 'TI', 'name' => 'Tirunelveli'],
                ['state_id' => $ids['TN'], 'code' => 'TJ', 'name' => 'Thanjavur'],
                ['state_id' => $ids['TN'], 'code' => 'TK', 'name' => 'Thoothukudi'],
                ['state_id' => $ids['TN'], 'code' => 'TL', 'name' => 'Tiruvallur'],
                ['state_id' => $ids['TN'], 'code' => 'TR', 'name' => 'Tiruvarur'],
                ['state_id' => $ids['TN'], 'code' => 'TV', 'name' => 'Tiruvannamalai'],
                ['state_id' => $ids['TN'], 'code' => 'VE', 'name' => 'Vellore'],
                ['state_id' => $ids['TN'], 'code' => 'VL', 'name' => 'Viluppuram'],
                ['state_id' => $ids['TN'], 'code' => 'VR', 'name' => 'Virudhunagar'],
                /* TELANGANA */
                ['state_id' => $ids['TS'], 'code' => 'AD', 'name' => 'Adilabad'],
                ['state_id' => $ids['TS'], 'code' => 'HY', 'name' => 'Hyderabad'],
                ['state_id' => $ids['TS'], 'code' => 'KA', 'name' => 'Karimnagar'],
                ['state_id' => $ids['TS'], 'code' => 'KH', 'name' => 'Khammam'],
                ['state_id' => $ids['TS'], 'code' => 'MA', 'name' => 'Mahbubnagar'],
                ['state_id' => $ids['TS'], 'code' => 'ME', 'name' => 'Medak'],
                ['state_id' => $ids['TS'], 'code' => 'NA', 'name' => 'Nalgonda'],
                ['state_id' => $ids['TS'], 'code' => 'NI', 'name' => 'Nizamabad'],
                ['state_id' => $ids['TS'], 'code' => 'RA', 'name' => 'Ranga Reddy'],
                ['state_id' => $ids['TS'], 'code' => 'WA', 'name' => 'Warangal'],
                /* TRIPURA */
                ['state_id' => $ids['TR'], 'code' => 'DH', 'name' => 'Dhalai'],
                ['state_id' => $ids['TR'], 'code' => 'GM', 'name' => 'Gomati'],
                ['state_id' => $ids['TR'], 'code' => 'KH', 'name' => 'Khowai'],
                ['state_id' => $ids['TR'], 'code' => 'NT', 'name' => 'North Tripura'],
                ['state_id' => $ids['TR'], 'code' => 'SP', 'name' => 'Sepahijala'],
                ['state_id' => $ids['TR'], 'code' => 'ST', 'name' => 'South Tripura'],
                ['state_id' => $ids['TR'], 'code' => 'UK', 'name' => 'Unokoti'],
                ['state_id' => $ids['TR'], 'code' => 'WT', 'name' => 'West Tripura'],
                /* UTTAR PRADESH */
                ['state_id' => $ids['UP'], 'code' => 'AG', 'name' => 'Agra'],
                ['state_id' => $ids['UP'], 'code' => 'AL', 'name' => 'Aligarh'],
                ['state_id' => $ids['UP'], 'code' => 'AH', 'name' => 'Allahabad'],
                ['state_id' => $ids['UP'], 'code' => 'AN', 'name' => 'Ambedkar Nagar'],
                ['state_id' => $ids['UP'], 'code' => 'CS', 'name' => 'Amethi(Chhatrapati Shahuji Maharaj Nagar)'],
                ['state_id' => $ids['UP'], 'code' => 'JP', 'name' => 'Amroha(Jyotiba Phule Nagar)'],
                ['state_id' => $ids['UP'], 'code' => 'AU', 'name' => 'Auraiya'],
                ['state_id' => $ids['UP'], 'code' => 'AZ', 'name' => 'Azamgarh'],
                ['state_id' => $ids['UP'], 'code' => 'BG', 'name' => 'Bagpat'],
                ['state_id' => $ids['UP'], 'code' => 'BH', 'name' => 'Bahraich'],
                ['state_id' => $ids['UP'], 'code' => 'BL', 'name' => 'Ballia'],
                ['state_id' => $ids['UP'], 'code' => 'BP', 'name' => 'Balrampur'],
                ['state_id' => $ids['UP'], 'code' => 'BN', 'name' => 'Banda'],
                ['state_id' => $ids['UP'], 'code' => 'BB', 'name' => 'Barabanki'],
                ['state_id' => $ids['UP'], 'code' => 'BR', 'name' => 'Bareilly'],
                ['state_id' => $ids['UP'], 'code' => 'BS', 'name' => 'Basti'],
                ['state_id' => $ids['UP'], 'code' => 'BI', 'name' => 'Bijnor'],
                ['state_id' => $ids['UP'], 'code' => 'BD', 'name' => 'Budaun'],
                ['state_id' => $ids['UP'], 'code' => 'BU', 'name' => 'Bulandshahr'],
                ['state_id' => $ids['UP'], 'code' => 'CD', 'name' => 'Chandauli'],
                ['state_id' => $ids['UP'], 'code' => 'CT', 'name' => 'Chitrakoot'],
                ['state_id' => $ids['UP'], 'code' => 'DE', 'name' => 'Deoria'],
                ['state_id' => $ids['UP'], 'code' => 'ET', 'name' => 'Etah'],
                ['state_id' => $ids['UP'], 'code' => 'EW', 'name' => 'Etawah'],
                ['state_id' => $ids['UP'], 'code' => 'FZ', 'name' => 'Faizabad'],
                ['state_id' => $ids['UP'], 'code' => 'FR', 'name' => 'Farrukhabad'],
                ['state_id' => $ids['UP'], 'code' => 'FT', 'name' => 'Fatehpur'],
                ['state_id' => $ids['UP'], 'code' => 'FI', 'name' => 'Firozabad'],
                ['state_id' => $ids['UP'], 'code' => 'GB', 'name' => 'Gautam Buddh Nagar'],
                ['state_id' => $ids['UP'], 'code' => 'GZ', 'name' => 'Ghaziabad'],
                ['state_id' => $ids['UP'], 'code' => 'GP', 'name' => 'Ghazipur'],
                ['state_id' => $ids['UP'], 'code' => 'GN', 'name' => 'Gonda'],
                ['state_id' => $ids['UP'], 'code' => 'GR', 'name' => 'Gorakhpur'],
                ['state_id' => $ids['UP'], 'code' => 'HM', 'name' => 'Hamirpur'],
                ['state_id' => $ids['UP'], 'code' => 'PN', 'name' => 'Hapur(Panchsheel Nagar)'],
                ['state_id' => $ids['UP'], 'code' => 'HR', 'name' => 'Hardoi'],
                ['state_id' => $ids['UP'], 'code' => 'HT', 'name' => 'Hathras(Mahamaya Nagar)'],
                ['state_id' => $ids['UP'], 'code' => 'JL', 'name' => 'Jalaun'],
                ['state_id' => $ids['UP'], 'code' => 'JU', 'name' => 'Jaunpur district'],
                ['state_id' => $ids['UP'], 'code' => 'JH', 'name' => 'Jhansi'],
                ['state_id' => $ids['UP'], 'code' => 'KJ', 'name' => 'Kannauj'],
                ['state_id' => $ids['UP'], 'code' => 'KD', 'name' => 'Kanpur Dehat(Ramabai Nagar)'],
                ['state_id' => $ids['UP'], 'code' => 'KN', 'name' => 'Kanpur Nagar'],
                ['state_id' => $ids['UP'], 'code' => 'KR', 'name' => 'Kasganj(Kanshi Ram Nagar)'],
                ['state_id' => $ids['UP'], 'code' => 'KS', 'name' => 'Kaushambi'],
                ['state_id' => $ids['UP'], 'code' => 'KU', 'name' => 'Kushinagar'],
                ['state_id' => $ids['UP'], 'code' => 'LK', 'name' => 'Lakhimpur Kheri'],
                ['state_id' => $ids['UP'], 'code' => 'LA', 'name' => 'Lalitpur'],
                ['state_id' => $ids['UP'], 'code' => 'LU', 'name' => 'Lucknow'],
                ['state_id' => $ids['UP'], 'code' => 'MG', 'name' => 'Mahoba'],
                ['state_id' => $ids['UP'], 'code' => 'MP', 'name' => 'Mainpuri'],
                ['state_id' => $ids['UP'], 'code' => 'MT', 'name' => 'Mathura'],
                ['state_id' => $ids['UP'], 'code' => 'MB', 'name' => 'Mau'],
                ['state_id' => $ids['UP'], 'code' => 'ME', 'name' => 'Meerut'],
                ['state_id' => $ids['UP'], 'code' => 'MI', 'name' => 'Mirzapur'],
                ['state_id' => $ids['UP'], 'code' => 'MO', 'name' => 'Moradabad'],
                ['state_id' => $ids['UP'], 'code' => 'MU', 'name' => 'Muzaffarnagar'],
                ['state_id' => $ids['UP'], 'code' => 'PI', 'name' => 'Pilibhit'],
                ['state_id' => $ids['UP'], 'code' => 'PR', 'name' => 'Pratapgarh'],
                ['state_id' => $ids['UP'], 'code' => 'RB', 'name' => 'Raebareli'],
                ['state_id' => $ids['UP'], 'code' => 'RA', 'name' => 'Rampur'],
                ['state_id' => $ids['UP'], 'code' => 'SA', 'name' => 'Sambhai'],
                ['state_id' => $ids['UP'], 'code' => 'SK', 'name' => 'Sant Kabir Nagar'],
                ['state_id' => $ids['UP'], 'code' => 'SR', 'name' => 'SJ'],
                ['state_id' => $ids['UP'], 'code' => 'SJ', 'name' => 'Shahjahanpur'],
                ['state_id' => $ids['UP'], 'code' => 'SH', 'name' => 'Shamli'],
                ['state_id' => $ids['UP'], 'code' => 'SV', 'name' => 'Shravasti'],
                ['state_id' => $ids['UP'], 'code' => 'SN', 'name' => 'Siddharthnagar'],
                ['state_id' => $ids['UP'], 'code' => 'SI', 'name' => 'Sitapur'],
                ['state_id' => $ids['UP'], 'code' => 'SO', 'name' => 'Sonbhadra'],
                ['state_id' => $ids['UP'], 'code' => 'SU', 'name' => 'Sultanpur'],
                ['state_id' => $ids['UP'], 'code' => 'UN', 'name' => 'Unnao'],
                ['state_id' => $ids['UP'], 'code' => 'VA', 'name' => 'Varanasi'],
                /* UTTARAKHAND */
                ['state_id' => $ids['UK'], 'code' => 'AL', 'name' => 'Almora'],
                ['state_id' => $ids['UK'], 'code' => 'BA', 'name' => 'Bageshwar'],
                ['state_id' => $ids['UK'], 'code' => 'CL', 'name' => 'Chamoli'],
                ['state_id' => $ids['UK'], 'code' => 'CP', 'name' => 'Champawat'],
                ['state_id' => $ids['UK'], 'code' => 'DD', 'name' => 'Dehradun'],
                ['state_id' => $ids['UK'], 'code' => 'HA', 'name' => 'Haridwar'],
                ['state_id' => $ids['UK'], 'code' => 'NA', 'name' => 'Naintal'],
                ['state_id' => $ids['UK'], 'code' => 'PG', 'name' => 'Pauri Garhwal'],
                ['state_id' => $ids['UK'], 'code' => 'PI', 'name' => 'Pithoragarh'],
                ['state_id' => $ids['UK'], 'code' => 'RP', 'name' => 'Rudraprayag'],
                ['state_id' => $ids['UK'], 'code' => 'TG', 'name' => 'Tehri Garhwal'],
                ['state_id' => $ids['UK'], 'code' => 'US', 'name' => 'Udham Singh Nagar'],
                ['state_id' => $ids['UK'], 'code' => 'UT', 'name' => 'Uttarkashi'],
                /* WEST BENGAL */
                ['state_id' => $ids['WB'], 'code' => 'AD', 'name' => 'Alipurduar'],
                ['state_id' => $ids['WB'], 'code' => 'BN', 'name' => 'Bankura'],
                ['state_id' => $ids['WB'], 'code' => 'BR', 'name' => 'Bardhaman'],
                ['state_id' => $ids['WB'], 'code' => 'BI', 'name' => 'Birbhum'],
                ['state_id' => $ids['WB'], 'code' => 'KB', 'name' => 'Cooch Behar'],
                ['state_id' => $ids['WB'], 'code' => 'DD', 'name' => 'Dakshin Dinajpur'],
                ['state_id' => $ids['WB'], 'code' => 'DA', 'name' => 'Darjeeling'],
                ['state_id' => $ids['WB'], 'code' => 'HG', 'name' => 'Hooghly'],
                ['state_id' => $ids['WB'], 'code' => 'HR', 'name' => 'Howrah'],
                ['state_id' => $ids['WB'], 'code' => 'JA', 'name' => 'Jalpaiguri'],
                ['state_id' => $ids['WB'], 'code' => 'KO', 'name' => 'Kolkata'],
                ['state_id' => $ids['WB'], 'code' => 'MA', 'name' => 'Maldah'],
                ['state_id' => $ids['WB'], 'code' => 'MSD', 'name' => 'Murshidabad'],
                ['state_id' => $ids['WB'], 'code' => 'NA', 'name' => 'Nadia'],
                ['state_id' => $ids['WB'], 'code' => 'PN', 'name' => 'North 24 Parganas'],
                ['state_id' => $ids['WB'], 'code' => 'PM', 'name' => 'Paschim Medinipur'],
                ['state_id' => $ids['WB'], 'code' => 'PR', 'name' => 'Purba Medinipur'],
                ['state_id' => $ids['WB'], 'code' => 'PU', 'name' => 'Purulia'],
                ['state_id' => $ids['WB'], 'code' => 'PS', 'name' => 'South 24 Parganas'],
                ['state_id' => $ids['WB'], 'code' => 'UD', 'name' => 'Uttar Dinajpur'],
            ]
        ); // end insert
    } // end run
}
